## MAIN

In [1]:
import pandas as pd
import numpy as np

df_clean = pd.read_csv('../Datasets/amazon_final.csv')
df_clean.head(10)

,product_title,product_rating,total_reviews,purchased_last_month,original_price,is_sponsored,coupon,buy_box_availability,sustainability_tags,product_image_url,...,badge_limited_time_deal,badge_no_badge,badge_save_xpct,product_category,log_purchased_last_month,product_segment,log_original_price,segment_Alta/Premium,segment_Baja,segment_Media
0,OWC 2.0TB Aura Pro X2 (GEN 4) SSD Complete Upg...,4.4,358.0,0,239.99,1,No Coupon,1,0,https://m.media-amazon.com/images/I/51vvx1JymA...,...,0,1,0,PC Components,0.000000,Media,5.484755,0,0,1
1,OWC 250GB Aura Pro 6G Flash SSD Upgrade for 20...,4.6,276.0,0,42.99,1,No Coupon,1,0,https://m.media-amazon.com/images/I/41d4RtiB8E...,...,0,1,0,Storage & Memory Cards,0.000000,Media,3.783962,0,0,1
2,HP 67XL Black High-yield Ink Cartridge | Works...,4.6,101072.0,50000,35.89,0,No Coupon,0,1,https://m.media-amazon.com/images/I/71y57XPIia...,...,0,0,0,"Office Supplies, Ink & Toner",10.819798,Media,3.607941,0,0,1
3,HP 67 Black/Tri-color Ink Cartridges for HP Pr...,4.6,59092.0,50000,43.89,0,No Coupon,0,0,https://m.media-amazon.com/images/I/51eBahpKda...,...,0,1,0,"Office Supplies, Ink & Toner",10.819798,Media,3.804215,0,0,1
4,"Sony ZX Series Wired On-Ear Headphones, Black ...",4.5,108926.0,10000,9.54,0,No Coupon,0,0,https://m.media-amazon.com/images/I/41CiQ7hR31...,...,0,0,0,"Audio, Sound & Recording Gear",9.210440,Baja,2.355178,0,1,0
5,Duracell Coppertop AA Batteries with Power Boo...,4.8,125404.0,80000,21.89,0,No Coupon,1,0,https://m.media-amazon.com/images/I/71F1yxjGeY...,...,0,1,0,Power & Batteries,11.289794,Media,3.130700,0,0,1
6,"Apple EarPods Headphones with USB-C Plug, Wire...",4.6,15087.0,10000,16.10,0,No Coupon,0,0,https://m.media-amazon.com/images/I/513OSdW4el...,...,0,1,0,Wearables,9.210440,Baja,2.839078,0,1,0
7,"Amazon Basics Wood-Cased #2 Pencils, Pre-sharp...",4.8,54244.0,100000,14.33,0,No Coupon,1,0,https://m.media-amazon.com/images/I/81qxJ-PgGL...,...,0,1,0,"Office Supplies, Ink & Toner",11.512935,Baja,2.729812,0,1,0
8,Apple Watch SE (2nd Gen) [GPS 40mm] Smartwatch...,4.6,12840.0,10000,146.14,0,No Coupon,0,0,https://m.media-amazon.com/images/I/61umEhyV-U...,...,0,1,0,Wearables,9.210440,Media,4.991385,0,0,1
9,Roku Streaming Stick HD 2025 — HD Streaming De...,4.6,1909.0,10000,33.51,0,No Coupon,0,1,https://m.media-amazon.com/images/I/71mye7IQ5j...,...,0,1,0,TV & Video Displays,9.210440,Baja,3.541249,0,1,0

In [5]:
df_clean = pd.read_csv('../Datasets/amazon_products_sales_data_cleaned.csv')
df_clean.head(1)

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.0,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.6

In [8]:
df_uncleaned.sustainability_badges.value_counts()

sustainability_badges
Small Business                    1341
Carbon impact                      769
Works with Alexa                   425
Energy efficiency                  262
Alexa Built-in                     184
Manufacturing practices            148
Energy efficiency +3 more          121
Energy efficiency +1 more           93
Forestry practices                  18
Safer chemicals +2 more             18
Recycled materials                   7
Recycled materials +2 more           7
Safer chemicals +1 more              6
Recycled materials +3 more           4
Made in Italy                        4
1 sustainability certification       1
Name: count, dtype: int64

In [7]:
df_clean.is_best_seller.value_counts()

is_best_seller
No Badge             40814
Amazon's               744
Limited time deal      409
Best Seller            275
Save 30%               125
Ends in                 97
Save 10%                61
Save 18%                57
Save 17%                51
Save 12%                26
Save 9%                 14
Save 77%                 2
Name: count, dtype: int64

### HAS_COUPON : 0/1
### AÑADIR DISCOUNT_COUPON: Integer: coupon value (%)
### DELIVERY DATE (ES UTIL????? QUITAR)