## MAIN

In [9]:
import pandas as pd
import numpy as np

df_uncleaned = pd.read_csv('../Datasets/amazon_products_sales_data_uncleaned.csv')
df_uncleaned.head(10)

,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,price_on_variant,listed_price,is_best_seller,is_sponsored,is_couponed,buy_box_availability,delivery_details,sustainability_badges,image_url,product_url,collected_at
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6 out of 5 stars,375,300+ bought in past month,89.68,basic variant price: 2.4GHz,$159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,"Delivery Mon, Sep 1",Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3 out of 5 stars,"2,457",6K+ bought in past month,9.99,basic variant price: nan,$15.99,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Fri, Aug 29",NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6 out of 5 stars,"3,044",2K+ bought in past month,314.00,basic variant price: nan,$349.00,No Badge,Sponsored,No Coupon,Add to cart,"Delivery Mon, Sep 1",NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...,2025-08-21 11:14:29
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6 out of 5 stars,"35,882",10K+ bought in past month,NaN,basic variant price: $162.24,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,/Apple-Cancellation-Transparency-Personalized-...,2025-08-21 11:14:29
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8 out of 5 stars,"28,988",10K+ bought in past month,NaN,basic variant price: $72.74,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,/Apple-MX542LL-A-AirTag-Pack/dp/B0D54JZTHY/ref...,2025-08-21 11:14:29
5,Texas Instruments TI-84 Plus CE Color Graphing...,4.6 out of 5 stars,"44,522",100K+ bought in past month,NaN,basic variant price: $99.95,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/71AyPChhFd...,/Texas-Instruments-TI-84-Graphing-Calculator/d...,2025-08-21 11:14:29
6,"Apple AirPods 4 Wireless Earbuds, Bluetooth He...",4.5 out of 5 stars,"13,466",10K+ bought in past month,NaN,basic variant price: $88.11,No Discount,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61iBtxCUab...,/Apple-Bluetooth-Headphones-Personalized-Effor...,2025-08-21 11:14:29
7,Apple AirTag. Keep Track of and find Your Keys...,4.6 out of 5 stars,"38,105",10K+ bought in past month,NaN,basic variant price: $23.04,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/71rP7f78eF...,/Apple-MX532LL-A-AirTag/dp/B0CWXNS552/ref=sr_1...,2025-08-21 11:14:29
8,Complete Protect: One plan covers all eligible...,4.0 out of 5 stars,"4,380",NaN,16.99,basic variant price: nan,No Discount,No Badge,Organic,Save 50% with coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/71tZ0n2xP9...,/Asurion-Complete-Protect/dp/B07RZ3LSHM/ref=sr...,2025-08-21 11:14:29
9,"Apple iPad 11-inch: A16 chip, 11-inch Model, L...",4.7 out of 5 stars,"7,308",10K+ bought in past month,NaN,basic variant price: $284.05,No Discount,Best Seller,Organic,No Coupon,NaN,NaN,Energy efficiency,https://m.media-amazon.com/images/I/61aPY8odPS...,/Apple-iPad-11-inch-Display-All-Day/dp/B0DZ75T...,2025-08-21 11:14:29

In [5]:
df_clean = pd.read_csv('../Datasets/amazon_products_sales_data_cleaned.csv')
df_clean.head(1)

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.0,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.6

In [8]:
df_uncleaned.sustainability_badges.value_counts()

sustainability_badges
Small Business                    1341
Carbon impact                      769
Works with Alexa                   425
Energy efficiency                  262
Alexa Built-in                     184
Manufacturing practices            148
Energy efficiency +3 more          121
Energy efficiency +1 more           93
Forestry practices                  18
Safer chemicals +2 more             18
Recycled materials                   7
Recycled materials +2 more           7
Safer chemicals +1 more              6
Recycled materials +3 more           4
Made in Italy                        4
1 sustainability certification       1
Name: count, dtype: int64

In [7]:
df_clean.is_best_seller.value_counts()

is_best_seller
No Badge             40814
Amazon's               744
Limited time deal      409
Best Seller            275
Save 30%               125
Ends in                 97
Save 10%                61
Save 18%                57
Save 17%                51
Save 12%                26
Save 9%                 14
Save 77%                 2
Name: count, dtype: int64

### HAS_COUPON : 0/1
### AÑADIR DISCOUNT_COUPON: Integer: coupon value (%)
### DELIVERY DATE (ES UTIL????? QUITAR)