## MAIN

In [2]:
import pandas as pd
import numpy as np

ev4 = pd.read_csv('../Datasets/evaluacion4_produccion.csv')
ev4.head(10)

,category,subtype,market_tier,condition,is_premium_brand,tech_generation,brand,confidence,printer_tech,is_color,...,buy_box_availability,sustainability_tags,has_coupon,discount_percentage,log_original_price,log_purchased_last_month,log_total_reviews,brand_subtype,image_url,product_url
0,PC Components (Core),ssd_internal,Mainstream,New,False,Current-Gen,OWC,0.95,NaN,NaN,...,1,0,0,0.00,5.484755,0.000000,5.883322,OWC_ssd_internal,https://m.media-amazon.com/images/I/51vvx1JymA...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...
1,PC Components (Core),ssd_internal,Mainstream,New,True,Current-Gen,OWC,0.95,NaN,NaN,...,1,0,0,0.00,3.783962,0.000000,5.624018,OWC_ssd_internal,https://m.media-amazon.com/images/I/41d4RtiB8E...,/sspa/click?ie=UTF8&spc=MTo4NzEzNDY2NTQ5NDYxND...
2,"Office, Printing & Power",toner_ink,Mainstream,New,True,Current-Gen,HP,0.95,Inkjet,False,...,0,1,0,0.00,3.607941,10.819798,11.523598,HP_toner_ink,https://m.media-amazon.com/images/I/71y57XPIia...,/HP-Cartridge-Black-3YM57AN-Tri-Color/dp/B0841...
3,"Office, Printing & Power",toner_ink,Mainstream,New,False,Current-Gen,HP,0.95,Inkjet,True,...,0,0,0,0.00,3.804215,10.819798,10.986868,HP_toner_ink,https://m.media-amazon.com/images/I/51eBahpKda...,/HP-Cartridges-Black-Tri-Color-3YP29AN/dp/B084...
4,Audio & Media Systems,headphones,Mainstream,New,False,Current-Gen,Sony,0.95,NaN,True,...,0,0,0,0.00,2.355178,9.210440,11.598433,Sony_headphones,https://m.media-amazon.com/images/I/41CiQ7hR31...,/Sony-MDRZX110-BLK-Stereo-Headphones/dp/B00NJ2...
5,"Office, Printing & Power",battery,Mainstream,New,False,Current-Gen,Duracell,0.95,NaN,NaN,...,1,0,0,0.14,3.130700,11.289794,11.739304,Duracell_battery,https://m.media-amazon.com/images/I/71F1yxjGeY...,NaN
6,Audio & Media Systems,earbuds,Mainstream,New,True,Current-Gen,Apple,0.95,NaN,NaN,...,0,0,0,0.00,2.839078,9.210440,9.621655,Apple_earbuds,https://m.media-amazon.com/images/I/513OSdW4el...,/Apple-EarPods-Headphones-Built-Control/dp/B0D...
7,Mobile Devices,smartwatch,Mainstream,New,True,Current-Gen,Apple,0.95,NaN,NaN,...,0,0,0,0.00,4.991385,9.210440,9.460398,Apple_smartwatch,https://m.media-amazon.com/images/I/61umEhyV-U...,/Apple-Smartwatch-Starlight-Aluminum-Detection...
8,Accessories,remote_control,Mainstream,New,False,Current-Gen,Roku,0.90,NaN,NaN,...,0,1,0,0.00,3.541249,9.210440,7.554859,Roku_remote_control,https://m.media-amazon.com/images/I/71mye7IQ5j...,/Roku-Streaming-Stick-HD-2025/dp/B0DXXYS4BJ/re...
9,"Office, Printing & Power",toner_ink,Mainstream,New,False,Current-Gen,Amazon Basics,0.90,NaN,NaN,...,1,0,0,0.00,2.889260,11.512935,11.396010,Amazon Basics_toner_ink,https://m.media-amazon.com/images/I/61cefAp7H5...,/AmazonBasics-Thermal-Laminating-Plastic-Lamin...

In [3]:
ev4.rename(columns={'image_url':'product_image_url'}, inplace=True)
ev4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6322 entries, 0 to 6321
Columns: 114 entries, category to product_url
dtypes: bool(2), float64(31), int64(3), object(78)
memory usage: 5.4+ MB

In [4]:
ev4.product_image_url

0       https://m.media-amazon.com/images/I/51vvx1JymA...
1       https://m.media-amazon.com/images/I/41d4RtiB8E...
2       https://m.media-amazon.com/images/I/71y57XPIia...
3       https://m.media-amazon.com/images/I/51eBahpKda...
4       https://m.media-amazon.com/images/I/41CiQ7hR31...
                              ...
6317    https://m.media-amazon.com/images/I/71RLbyxkUp...
6318    https://m.media-amazon.com/images/I/81bLVfMTrN...
6319    https://m.media-amazon.com/images/I/81U+SuxDL9...
6320    https://m.media-amazon.com/images/I/71IrtnjZD2...
6321    https://m.media-amazon.com/images/I/71wTn+zoSr...
Name: product_image_url, Length: 6322, dtype: object

In [5]:
ev4.to_csv('../Datasets/evaluacion4_produccion.csv', index=False)

In [6]:
dashb = pd.read_csv("data_dashboard.csv")
dashb.head()

,category,subtype,market_tier,condition,is_premium_brand,tech_generation,brand,confidence,printer_tech,is_color,...,is_best_seller,is_sponsored,buy_box_availability,sustainability_tags,has_coupon,discount_percentage,log_original_price,log_purchased_last_month,log_total_reviews,product_image_url
0,PC Components (Core),ssd_internal,Mainstream,New,False,Current-Gen,OWC,0.95,NaN,NaN,...,No Badge,Sponsored,1,0,0,0.0,5.484755,0.000000,5.883322,https://m.media-amazon.com/images/I/51vvx1JymA...
1,PC Components (Core),ssd_internal,Mainstream,New,True,Current-Gen,OWC,0.95,NaN,NaN,...,No Badge,Sponsored,1,0,0,0.0,3.783962,0.000000,5.624018,https://m.media-amazon.com/images/I/41d4RtiB8E...
2,"Office, Printing & Power",toner_ink,Mainstream,New,True,Current-Gen,HP,0.95,Inkjet,False,...,Best Seller,Organic,0,1,0,0.0,3.607941,10.819798,11.523598,https://m.media-amazon.com/images/I/71y57XPIia...
3,"Office, Printing & Power",toner_ink,Mainstream,New,False,Current-Gen,HP,0.95,Inkjet,True,...,No Badge,Organic,0,0,0,0.0,3.804215,10.819798,10.986868,https://m.media-amazon.com/images/I/51eBahpKda...
4,Audio & Media Systems,headphones,Mainstream,New,False,Current-Gen,Sony,0.95,NaN,True,...,Best Seller,Organic,0,0,0,0.0,2.355178,9.210440,11.598433,https://m.media-amazon.com/images/I/41CiQ7hR31...

In [8]:
def info_df(df):
    return pd.DataFrame({
    'Columna': df.columns,
    'No Nulos': df.notnull().sum().values,
    'Nulos': df.isnull().sum().values,
    'Tipo Python': df.dtypes.values,
    'Núm. valores': [len(df[col].unique()) for col in df.columns]
     })
info = info_df(dashb)
info

                      Columna  No Nulos  Nulos Tipo Python  Núm. valores
0                    category      6445      0      object            10
1                     subtype      6445      0      object            98
2                 market_tier      6445      0      object             4
3                   condition      6445      0      object             2
4            is_premium_brand      6445      0        bool             2
..                        ...       ...    ...         ...           ...
110       discount_percentage      6445      0     float64            71
111        log_original_price      6445      0     float64          2656
112  log_purchased_last_month      6445      0     float64            30
113         log_total_reviews      6445      0     float64          3509
114         product_image_url      6445      0      object          6343

[115 rows x 5 columns]

In [7]:
cols_dashb_not_ev4 = set(dashb.columns) - set(ev4.columns)
print(cols_dashb_not_ev4)

{'original_title', 'product_image_url'}

In [12]:
df_clean['total_reviews'] = np.exp(df_clean['log_total_reviews'])

In [ ]:
df_clean[(df_clean.category == 'Office, Printing & Power') & (df_clean.subtype == 'printer') & (df_clean.brand == 'Canon' )]

In [5]:
df_clean = pd.read_csv('../Datasets/amazon_products_sales_data_cleaned.csv')
df_clean.head(1)

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.0,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.6

In [8]:
df_uncleaned.sustainability_badges.value_counts()

sustainability_badges
Small Business                    1341
Carbon impact                      769
Works with Alexa                   425
Energy efficiency                  262
Alexa Built-in                     184
Manufacturing practices            148
Energy efficiency +3 more          121
Energy efficiency +1 more           93
Forestry practices                  18
Safer chemicals +2 more             18
Recycled materials                   7
Recycled materials +2 more           7
Safer chemicals +1 more              6
Recycled materials +3 more           4
Made in Italy                        4
1 sustainability certification       1
Name: count, dtype: int64

In [7]:
df_clean.is_best_seller.value_counts()

is_best_seller
No Badge             40814
Amazon's               744
Limited time deal      409
Best Seller            275
Save 30%               125
Ends in                 97
Save 10%                61
Save 18%                57
Save 17%                51
Save 12%                26
Save 9%                 14
Save 77%                 2
Name: count, dtype: int64

### HAS_COUPON : 0/1
### AÑADIR DISCOUNT_COUPON: Integer: coupon value (%)
### DELIVERY DATE (ES UTIL????? QUITAR)