In [14]:
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
import datetime
import math
from scipy import stats

In [16]:
df = pd.read_csv("../Datasets/amazon_final.csv")

In [18]:
def info_df(df):
    return pd.DataFrame({
    'Columna': df.columns,
    'No Nulos': df.notnull().sum().values,
    'Nulos': df.isnull().sum().values,
    'Tipo Python': df.dtypes.values,
    'Núm. valores': [len(df[col].unique()) for col in df.columns]
     })
info = info_df(df)
info

                 Columna  No Nulos  Nulos Tipo Python  Núm. valores
0          product_title     42675      0      object          8808
1         product_rating     41651   1024     float64            32
2          total_reviews     41651   1024     float64          4414
3   purchased_last_month     32164  10511     float64            30
4       discounted_price     40613   2062     float64          3559
5         original_price     40613   2062     float64          3152
6         is_best_seller     42675      0      object            12
7           is_sponsored     42675      0      object             2
8                 coupon     42675      0      object            42
9   buy_box_availability     42675      0       int64             2
10   sustainability_tags      3408  39267      object            17
11     product_image_url     42675      0      object          8038
12            has_coupon     42675      0       int64             2
13      product_category     42675      0      object            20
14   discount_percentage     40613   2062     float64          1527

In [20]:
peripherals = df[df['product_category'] == 'Computer Peripherals'].copy()
info = info_df(peripherals)
info

                 Columna  No Nulos  Nulos Tipo Python  Núm. valores
0          product_title      3517      0      object           783
1         product_rating      3476     41     float64            20
2          total_reviews      3476     41     float64           689
3   purchased_last_month      2703    814     float64            20
4       discounted_price      2993    524     float64           466
5         original_price      2993    524     float64           374
6         is_best_seller      3517      0      object             5
7           is_sponsored      3517      0      object             2
8                 coupon      3517      0      object            10
9   buy_box_availability      3517      0       int64             2
10   sustainability_tags       332   3185      object             8
11     product_image_url      3517      0      object           776
12            has_coupon      3517      0       int64             2
13      product_category      3517      0      object             1
14   discount_percentage      2993    524     float64           237

In [ ]:
from IPython.display import Image, HTML

# 1. Definimos una función que envuelve la URL en una etiqueta HTML <img>
def render_image(url):
    return f'<img src="{url}" width="80" >'

# 2. Seleccionamos la muestra
sample_peripherals = df[df['category'] == 'Computer Peripherals'][['product_title', 'image_url', 'listed_price']].sample(15)

# 3. Mostramos la tabla renderizando el HTML
# 'escape=False' permite que el navegador lea los tags <img> en lugar de verlos como texto
HTML(sample_peripherals.to_html(escape=False, formatters=dict(image_url=render_image)))

KeyError: 'category'